# Generated by Django 3.2.18 on 2023-04-12 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0005_alter_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
