# Generated by Django 3.2.18 on 2023-04-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0006_auto_20230412_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='excerpt',
            new_name='body',
        ),
    ]
