# Generated by Django 3.2.18 on 2023-04-17 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0007_rename_excerpt_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
    ]
