# Generated by Django 3.2.18 on 2023-04-19 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0009_remove_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
